//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TakYabEntities : DbContext
    {
        public TakYabEntities()
            : base("name=TakYabEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdType> AdTypes { get; set; }
        public DbSet<BuildYear> BuildYears { get; set; }
        public DbSet<Model> Models { get; set; }
        public DbSet<Priority> Priorities { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<SubModel> SubModels { get; set; }
        public DbSet<AdStatus> AdStatus { get; set; }
        public DbSet<Colour> Colours { get; set; }
        public DbSet<InsuranceType> InsuranceTypes { get; set; }
        public DbSet<FuelType> FuelTypes { get; set; }
        public DbSet<CarStatus> CarStatus { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<PriceRange> PriceRanges { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<CarView> CarViews { get; set; }
        public DbSet<FavouritCar> FavouritCars { get; set; }
    }
}
